# Generated by Django 5.1.3 on 2024-11-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0009_alter_automobilo_modelis_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Automobilo_modelis',
            new_name='AutomobiloModelis',
        ),
        migrations.RenameModel(
            old_name='Uzsakymo_eilute',
            new_name='UzsakymoEilute',
        ),
        migrations.AlterModelOptions(
            name='automobilis',
            options={'verbose_name_plural': 'Automobiliai'},
        ),
        migrations.AlterModelOptions(
            name='automobilomodelis',
            options={'verbose_name': 'Automobilio Modelis', 'verbose_name_plural': 'Automobilio modeliai'},
        ),
        migrations.AlterModelOptions(
            name='paslauga',
            options={'verbose_name': 'Paslauga', 'verbose_name_plural': 'Paslaugos'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'ordering': ['data'], 'verbose_name_plural': 'Uzsakymai'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymoeilute',
            options={'verbose_name': 'Uzsakymo eilutes', 'verbose_name_plural': 'Uzsakymo eilute'},
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('Uzregistruotas', 'Uzregistruota'), ('Eileje', 'Eileje'), ('Tvarkomas', 'Tvarkoma'), ('Galima atsiimti', 'Galima atsiimti')], default='uzregistruotas', help_text='Statusas', max_length=20),
        ),
    ]
