# Generated by Django 5.1.3 on 2024-11-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0010_rename_automobilo_modelis_automobilomodelis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('uzregistruotas', 'Uzregistruota'), ('eileje', 'Eileje'), ('tvarkomas', 'Tvarkoma'), ('galima atsiimti', 'Galima atsiimti'), ('atlikta', 'Atlikta')], default='Uzregistruotas', help_text='Statusas', max_length=20),
        ),
    ]
