# Generated by Django 5.1.3 on 2024-12-03 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0011_alter_uzsakymas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilis',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Viršelis'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='automobilio_modelis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automobiliomodelis', to='autoservice.automobilomodelis'),
        ),
    ]
