# Generated by Django 5.1.3 on 2024-12-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0012_automobilis_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilis',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Viršelis'),
        ),
    ]
