# Generated by Django 5.1.3 on 2024-12-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0014_uzsakymas_reader_alter_uzsakymas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Bus sutvarkyta'),
        ),
    ]
