# Generated by Django 5.1.3 on 2024-12-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0015_alter_uzsakymas_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzsakymas',
            old_name='reader',
            new_name='savininkas',
        ),
    ]
