# Generated by Django 5.1.3 on 2024-12-05 11:38

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0017_uzsakymas_bus_sutvarkyta_alter_uzsakymas_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'ordering': ['bus_sutvarkyta'], 'verbose_name_plural': 'Uzsakymai'},
        ),
        migrations.AddField(
            model_name='automobilis',
            name='aprasymas',
            field=tinymce.models.HTMLField(help_text='Aprasymas', null=True, verbose_name='Aprasymas'),
        ),
    ]
