# Generated by Django 5.1.3 on 2024-12-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0020_custumerreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustumerReview',
        ),
    ]
