# Generated by Django 5.1.3 on 2024-12-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0022_custumerreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custumerreview',
            name='uzsakymas',
        ),
    ]
