# Generated by Django 5.1.3 on 2024-12-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0024_naujienos_delete_custumerreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Naujienos',
            new_name='Akcijos',
        ),
    ]
